services:
  pg:
    image: postgres:16-alpine
    container_name: pg
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d studs"]
      interval: 5s
      timeout: 3s
      retries: 15
    restart: unless-stopped

volumes:
  pgdata:
