version: "3.9"

services:
  pg:
    image: postgres:16-alpine
    container_name: pg
    env_file:
      - .env
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 15
    restart: unless-stopped

  backend:
    depends_on:
      pg:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL:-jdbc:postgresql://pg:5432/studs}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS:-postgres}
      SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
      SPRING_FLYWAY_ENABLED: "true"
    restart: unless-stopped

volumes:
  pgdata:
